### PR TITLE
RTC implementation, stdlib replacement cleanup, revert recent USB changes

### PR DESCRIPTION
**Pull request by snhirsch**
Hi, Skip.

When you get a chance, would appreciate your looking this over.  I started by reverting the most recent set of changes to the USB subsystem, then applying my work on top of that.  If you hit Enter at the time / date prompt, behavior will be the same as it is at present.

### CODE REVIEW

**Comment by skiphansen** [comment]
Did reverting the USB changes fix the errors you were seeing?

**Comment by snhirsch** [comment]
It makes it slightly more stable, but still flakes out after a bit of use.
The head revision was hopeless, at least for my combination of Pano and USB
drive.  I can send you my entire z80pack disk set with instructions on how
to invariably trigger it.  Would that help?

**Comment by skiphansen** [comment]
Having a copy of your z80pack would be great, I've haven't gotten around to installing the Z system yet.  

I really don't like the idea of the mass revert of the USB changes.  When possible each commit should target one feature or bug.  Many of the USB changes are what should be benign logging changes.  

The intent of that commit (to fix the USB port next to the Ethernet jack) definitely shouldn't have effected anything not plugged into that port.  The other change to enable support for external hubs shouldn't have effected anything either. 

One change I made while attempting to fix the first port was to put the hub into Multi-TT mode.  It didn't fix the first port issue, but I left it in anyway.  I think that may be causing problems.  I'll revert it today, hopefully that will fix the regression.

**Comment by skiphansen** [comment]
I've reverted the multi-TT changes, please give it a try and let me know what you find.

**Comment by snhirsch** [comment]
No problem on the USB revert - I just did that in order to have a chance at testing things here.  I will roll it back in to my fork.  ISTR that the recent USB changes also affected the lower ports, but I'll re-check that.

**Comment by snhirsch** [comment]
I reverted the backout of the USB changes for 103f5715b and merged your most recent commits into my fork.  I'm now operating with your latest hardware bitstream and my modified firmware (RTC and cleanup fixes only).  It's not usable here.  I get almost immediate cascades of USB, disk_read and dco_out errors.  This occurs with upper or lower USB connectors.  I'll contact you privately with a link to my z80pack disk images and instructions for reproducing the issue I'm seeing.

**Comment by skiphansen** [comment]
Drat!  Please send me your image and I'll do some testing tonight.  If nothing else I should be able to figure out what change made it worse.  I also see error eventually, but nothing is repeatable enough to make any meaningful A/B comparisons.

**Comment by skiphansen** [comment]
I'm very confused! Reviewing the changes on github's website I don't see any changes to usb.c.  However if I checkout both repositories and compare them locally I find differences in usb.c.  

Specifically here's is first difference:
https://github.com/snhirsch/pano_z80/blob/master/fw/firmware/usb.c#L87
vrs
https://github.com/skiphansen/pano_z80/blob/master/fw/firmware/usb.c#L87

So it appears that this pull request reverts commit:
https://github.com/skiphansen/pano_z80/commit/5fce48746f1441563482278c9bd96aa6f4d0d13b

That commit was a shot in the dark which didn't work anyway so it's not a big deal, but now I don't trust the github tools.

**Comment by snhirsch** [comment]
Ooof.  That's not helpful, is it?  We used Git very heavily in my last job, both at the command line and via a GitLab server.  Don't recall ever tripping over anything like this.

**Comment by skiphansen** [comment]
I don't use the web gui that much, but I've never seen any think like it either.  I didn't want to merge until you saw that I wasn't  hallucinating!

Your changes look fine.   Thanks for adding to the project!
Do you have any feel for how does the long term clock accuracy is?  i.e. if left running for 24 hours how far off is the RTC?

**Pull request merged**
